/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteRouteImport } from './routes/onboarding/route'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as R2SplatRouteImport } from './routes/r2.$'
import { Route as OnboardingVerifyRouteImport } from './routes/onboarding/verify'
import { Route as LiveSlugRouteImport } from './routes/live.$slug'
import { Route as PublicSupportRouteImport } from './routes/_public/support'
import { Route as PublicSRouteImport } from './routes/_public/s'
import { Route as PublicPricingRouteImport } from './routes/_public/pricing'
import { Route as PublicHomeRouteImport } from './routes/_public/home'
import { Route as PublicBlocksShowcaseRouteImport } from './routes/_public/blocks-showcase'
import { Route as PublicAboutUsRouteImport } from './routes/_public/about-us'
import { Route as PublicSplatRouteImport } from './routes/_public/$'
import { Route as AuthMagicCodeRouteImport } from './routes/_auth/magic-code'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as OOrgIdRouteRouteImport } from './routes/o.$orgId/route'
import { Route as OOrgIdIndexRouteImport } from './routes/o.$orgId/index'
import { Route as PublicDiscoverIndexRouteImport } from './routes/_public/discover/index'
import { Route as OOrgIdPaymentsRouteImport } from './routes/o.$orgId/payments'
import { Route as OOrgIdFinanceRouteImport } from './routes/o.$orgId/finance'
import { Route as OOrgIdDonationsRouteImport } from './routes/o.$orgId/donations'
import { Route as OOrgIdCampaignsRouteImport } from './routes/o.$orgId/campaigns'
import { Route as OOrgIdAccountRouteImport } from './routes/o.$orgId/account'
import { Route as FSlugDonateRouteImport } from './routes/f.$slug.donate'
import { Route as DDonationIdDonationStatusRouteImport } from './routes/d.$donationId.donation-status'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as PublicDiscoverCategoryRouteImport } from './routes/_public/discover/$category'
import { Route as PublicDDonationIdRouteImport } from './routes/_public/d.$donationId'
import { Route as OOrgIdPaymentsIndexRouteImport } from './routes/o.$orgId/payments/index'
import { Route as OOrgIdCampaignsIndexRouteImport } from './routes/o.$orgId/campaigns/index'
import { Route as OOrgIdAccountIndexRouteImport } from './routes/o.$orgId/account/index'
import { Route as PublicFSlugIndexRouteImport } from './routes/_public/f.$slug/index'
import { Route as OOrgIdPaymentsWithdrawalHistoryRouteImport } from './routes/o.$orgId/payments/withdrawal-history'
import { Route as OOrgIdPaymentsWithdrawalAccountsRouteImport } from './routes/o.$orgId/payments/withdrawal-accounts'
import { Route as OOrgIdCampaignsCampaignIdRouteImport } from './routes/o.$orgId/campaigns.$campaignId'
import { Route as OOrgIdCampaignPreviewsCampaignIdRouteImport } from './routes/o.$orgId/campaign-previews.$campaignId'
import { Route as OOrgIdAccountSecurityRouteImport } from './routes/o.$orgId/account/security'
import { Route as OOrgIdAccountKycRouteImport } from './routes/o.$orgId/account/kyc'
import { Route as OOrgIdCampaignsCampaignIdIndexRouteImport } from './routes/o.$orgId/campaigns.$campaignId/index'
import { Route as OOrgIdCampaignsCampaignIdSharingRouteImport } from './routes/o.$orgId/campaigns.$campaignId/sharing'
import { Route as OOrgIdCampaignsCampaignIdSettingsRouteImport } from './routes/o.$orgId/campaigns.$campaignId/settings'

const OnboardingRouteRoute = OnboardingRouteRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const R2SplatRoute = R2SplatRouteImport.update({
  id: '/r2/$',
  path: '/r2/$',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingVerifyRoute = OnboardingVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const LiveSlugRoute = LiveSlugRouteImport.update({
  id: '/live/$slug',
  path: '/live/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicSupportRoute = PublicSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicSRoute = PublicSRouteImport.update({
  id: '/s',
  path: '/s',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicPricingRoute = PublicPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicHomeRoute = PublicHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicBlocksShowcaseRoute = PublicBlocksShowcaseRouteImport.update({
  id: '/blocks-showcase',
  path: '/blocks-showcase',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicAboutUsRoute = PublicAboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicSplatRoute = PublicSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AuthMagicCodeRoute = AuthMagicCodeRouteImport.update({
  id: '/magic-code',
  path: '/magic-code',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const OOrgIdRouteRoute = OOrgIdRouteRouteImport.update({
  id: '/o/$orgId',
  path: '/o/$orgId',
  getParentRoute: () => rootRouteImport,
} as any)
const OOrgIdIndexRoute = OOrgIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OOrgIdRouteRoute,
} as any).lazy(() =>
  import('./routes/o.$orgId/index.lazy').then((d) => d.Route),
)
const PublicDiscoverIndexRoute = PublicDiscoverIndexRouteImport.update({
  id: '/discover/',
  path: '/discover/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const OOrgIdPaymentsRoute = OOrgIdPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => OOrgIdRouteRoute,
} as any)
const OOrgIdFinanceRoute = OOrgIdFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => OOrgIdRouteRoute,
} as any).lazy(() =>
  import('./routes/o.$orgId/finance.lazy').then((d) => d.Route),
)
const OOrgIdDonationsRoute = OOrgIdDonationsRouteImport.update({
  id: '/donations',
  path: '/donations',
  getParentRoute: () => OOrgIdRouteRoute,
} as any)
const OOrgIdCampaignsRoute = OOrgIdCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => OOrgIdRouteRoute,
} as any)
const OOrgIdAccountRoute = OOrgIdAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => OOrgIdRouteRoute,
} as any)
const FSlugDonateRoute = FSlugDonateRouteImport.update({
  id: '/f/$slug/donate',
  path: '/f/$slug/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const DDonationIdDonationStatusRoute =
  DDonationIdDonationStatusRouteImport.update({
    id: '/d/$donationId/donation-status',
    path: '/d/$donationId/donation-status',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicDiscoverCategoryRoute = PublicDiscoverCategoryRouteImport.update({
  id: '/discover/$category',
  path: '/discover/$category',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicDDonationIdRoute = PublicDDonationIdRouteImport.update({
  id: '/d/$donationId',
  path: '/d/$donationId',
  getParentRoute: () => PublicRouteRoute,
} as any)
const OOrgIdPaymentsIndexRoute = OOrgIdPaymentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OOrgIdPaymentsRoute,
} as any)
const OOrgIdCampaignsIndexRoute = OOrgIdCampaignsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OOrgIdCampaignsRoute,
} as any)
const OOrgIdAccountIndexRoute = OOrgIdAccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OOrgIdAccountRoute,
} as any)
const PublicFSlugIndexRoute = PublicFSlugIndexRouteImport.update({
  id: '/f/$slug/',
  path: '/f/$slug/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const OOrgIdPaymentsWithdrawalHistoryRoute =
  OOrgIdPaymentsWithdrawalHistoryRouteImport.update({
    id: '/withdrawal-history',
    path: '/withdrawal-history',
    getParentRoute: () => OOrgIdPaymentsRoute,
  } as any)
const OOrgIdPaymentsWithdrawalAccountsRoute =
  OOrgIdPaymentsWithdrawalAccountsRouteImport.update({
    id: '/withdrawal-accounts',
    path: '/withdrawal-accounts',
    getParentRoute: () => OOrgIdPaymentsRoute,
  } as any)
const OOrgIdCampaignsCampaignIdRoute =
  OOrgIdCampaignsCampaignIdRouteImport.update({
    id: '/$campaignId',
    path: '/$campaignId',
    getParentRoute: () => OOrgIdCampaignsRoute,
  } as any)
const OOrgIdCampaignPreviewsCampaignIdRoute =
  OOrgIdCampaignPreviewsCampaignIdRouteImport.update({
    id: '/campaign-previews/$campaignId',
    path: '/campaign-previews/$campaignId',
    getParentRoute: () => OOrgIdRouteRoute,
  } as any)
const OOrgIdAccountSecurityRoute = OOrgIdAccountSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => OOrgIdAccountRoute,
} as any)
const OOrgIdAccountKycRoute = OOrgIdAccountKycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => OOrgIdAccountRoute,
} as any)
const OOrgIdCampaignsCampaignIdIndexRoute =
  OOrgIdCampaignsCampaignIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => OOrgIdCampaignsCampaignIdRoute,
  } as any).lazy(() =>
    import('./routes/o.$orgId/campaigns.$campaignId/index.lazy').then(
      (d) => d.Route,
    ),
  )
const OOrgIdCampaignsCampaignIdSharingRoute =
  OOrgIdCampaignsCampaignIdSharingRouteImport.update({
    id: '/sharing',
    path: '/sharing',
    getParentRoute: () => OOrgIdCampaignsCampaignIdRoute,
  } as any)
const OOrgIdCampaignsCampaignIdSettingsRoute =
  OOrgIdCampaignsCampaignIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => OOrgIdCampaignsCampaignIdRoute,
  } as any).lazy(() =>
    import('./routes/o.$orgId/campaigns.$campaignId/settings.lazy').then(
      (d) => d.Route,
    ),
  )

export interface FileRoutesByFullPath {
  '/onboarding': typeof OnboardingRouteRouteWithChildren
  '/o/$orgId': typeof OOrgIdRouteRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/magic-code': typeof AuthMagicCodeRoute
  '/$': typeof PublicSplatRoute
  '/about-us': typeof PublicAboutUsRoute
  '/blocks-showcase': typeof PublicBlocksShowcaseRoute
  '/home': typeof PublicHomeRoute
  '/pricing': typeof PublicPricingRoute
  '/s': typeof PublicSRoute
  '/support': typeof PublicSupportRoute
  '/live/$slug': typeof LiveSlugRoute
  '/onboarding/verify': typeof OnboardingVerifyRoute
  '/r2/$': typeof R2SplatRoute
  '/': typeof PublicIndexRoute
  '/app': typeof AppIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/d/$donationId': typeof PublicDDonationIdRoute
  '/discover/$category': typeof PublicDiscoverCategoryRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/d/$donationId/donation-status': typeof DDonationIdDonationStatusRoute
  '/f/$slug/donate': typeof FSlugDonateRoute
  '/o/$orgId/account': typeof OOrgIdAccountRouteWithChildren
  '/o/$orgId/campaigns': typeof OOrgIdCampaignsRouteWithChildren
  '/o/$orgId/donations': typeof OOrgIdDonationsRoute
  '/o/$orgId/finance': typeof OOrgIdFinanceRoute
  '/o/$orgId/payments': typeof OOrgIdPaymentsRouteWithChildren
  '/discover': typeof PublicDiscoverIndexRoute
  '/o/$orgId/': typeof OOrgIdIndexRoute
  '/o/$orgId/account/kyc': typeof OOrgIdAccountKycRoute
  '/o/$orgId/account/security': typeof OOrgIdAccountSecurityRoute
  '/o/$orgId/campaign-previews/$campaignId': typeof OOrgIdCampaignPreviewsCampaignIdRoute
  '/o/$orgId/campaigns/$campaignId': typeof OOrgIdCampaignsCampaignIdRouteWithChildren
  '/o/$orgId/payments/withdrawal-accounts': typeof OOrgIdPaymentsWithdrawalAccountsRoute
  '/o/$orgId/payments/withdrawal-history': typeof OOrgIdPaymentsWithdrawalHistoryRoute
  '/f/$slug': typeof PublicFSlugIndexRoute
  '/o/$orgId/account/': typeof OOrgIdAccountIndexRoute
  '/o/$orgId/campaigns/': typeof OOrgIdCampaignsIndexRoute
  '/o/$orgId/payments/': typeof OOrgIdPaymentsIndexRoute
  '/o/$orgId/campaigns/$campaignId/settings': typeof OOrgIdCampaignsCampaignIdSettingsRoute
  '/o/$orgId/campaigns/$campaignId/sharing': typeof OOrgIdCampaignsCampaignIdSharingRoute
  '/o/$orgId/campaigns/$campaignId/': typeof OOrgIdCampaignsCampaignIdIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof AuthLoginRoute
  '/magic-code': typeof AuthMagicCodeRoute
  '/$': typeof PublicSplatRoute
  '/about-us': typeof PublicAboutUsRoute
  '/blocks-showcase': typeof PublicBlocksShowcaseRoute
  '/home': typeof PublicHomeRoute
  '/pricing': typeof PublicPricingRoute
  '/s': typeof PublicSRoute
  '/support': typeof PublicSupportRoute
  '/live/$slug': typeof LiveSlugRoute
  '/onboarding/verify': typeof OnboardingVerifyRoute
  '/r2/$': typeof R2SplatRoute
  '/': typeof PublicIndexRoute
  '/app': typeof AppIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/d/$donationId': typeof PublicDDonationIdRoute
  '/discover/$category': typeof PublicDiscoverCategoryRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/d/$donationId/donation-status': typeof DDonationIdDonationStatusRoute
  '/f/$slug/donate': typeof FSlugDonateRoute
  '/o/$orgId/donations': typeof OOrgIdDonationsRoute
  '/o/$orgId/finance': typeof OOrgIdFinanceRoute
  '/discover': typeof PublicDiscoverIndexRoute
  '/o/$orgId': typeof OOrgIdIndexRoute
  '/o/$orgId/account/kyc': typeof OOrgIdAccountKycRoute
  '/o/$orgId/account/security': typeof OOrgIdAccountSecurityRoute
  '/o/$orgId/campaign-previews/$campaignId': typeof OOrgIdCampaignPreviewsCampaignIdRoute
  '/o/$orgId/payments/withdrawal-accounts': typeof OOrgIdPaymentsWithdrawalAccountsRoute
  '/o/$orgId/payments/withdrawal-history': typeof OOrgIdPaymentsWithdrawalHistoryRoute
  '/f/$slug': typeof PublicFSlugIndexRoute
  '/o/$orgId/account': typeof OOrgIdAccountIndexRoute
  '/o/$orgId/campaigns': typeof OOrgIdCampaignsIndexRoute
  '/o/$orgId/payments': typeof OOrgIdPaymentsIndexRoute
  '/o/$orgId/campaigns/$campaignId/settings': typeof OOrgIdCampaignsCampaignIdSettingsRoute
  '/o/$orgId/campaigns/$campaignId/sharing': typeof OOrgIdCampaignsCampaignIdSharingRoute
  '/o/$orgId/campaigns/$campaignId': typeof OOrgIdCampaignsCampaignIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/onboarding': typeof OnboardingRouteRouteWithChildren
  '/o/$orgId': typeof OOrgIdRouteRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/magic-code': typeof AuthMagicCodeRoute
  '/_public/$': typeof PublicSplatRoute
  '/_public/about-us': typeof PublicAboutUsRoute
  '/_public/blocks-showcase': typeof PublicBlocksShowcaseRoute
  '/_public/home': typeof PublicHomeRoute
  '/_public/pricing': typeof PublicPricingRoute
  '/_public/s': typeof PublicSRoute
  '/_public/support': typeof PublicSupportRoute
  '/live/$slug': typeof LiveSlugRoute
  '/onboarding/verify': typeof OnboardingVerifyRoute
  '/r2/$': typeof R2SplatRoute
  '/_public/': typeof PublicIndexRoute
  '/app/': typeof AppIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/_public/d/$donationId': typeof PublicDDonationIdRoute
  '/_public/discover/$category': typeof PublicDiscoverCategoryRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/d/$donationId/donation-status': typeof DDonationIdDonationStatusRoute
  '/f/$slug/donate': typeof FSlugDonateRoute
  '/o/$orgId/account': typeof OOrgIdAccountRouteWithChildren
  '/o/$orgId/campaigns': typeof OOrgIdCampaignsRouteWithChildren
  '/o/$orgId/donations': typeof OOrgIdDonationsRoute
  '/o/$orgId/finance': typeof OOrgIdFinanceRoute
  '/o/$orgId/payments': typeof OOrgIdPaymentsRouteWithChildren
  '/_public/discover/': typeof PublicDiscoverIndexRoute
  '/o/$orgId/': typeof OOrgIdIndexRoute
  '/o/$orgId/account/kyc': typeof OOrgIdAccountKycRoute
  '/o/$orgId/account/security': typeof OOrgIdAccountSecurityRoute
  '/o/$orgId/campaign-previews/$campaignId': typeof OOrgIdCampaignPreviewsCampaignIdRoute
  '/o/$orgId/campaigns/$campaignId': typeof OOrgIdCampaignsCampaignIdRouteWithChildren
  '/o/$orgId/payments/withdrawal-accounts': typeof OOrgIdPaymentsWithdrawalAccountsRoute
  '/o/$orgId/payments/withdrawal-history': typeof OOrgIdPaymentsWithdrawalHistoryRoute
  '/_public/f/$slug/': typeof PublicFSlugIndexRoute
  '/o/$orgId/account/': typeof OOrgIdAccountIndexRoute
  '/o/$orgId/campaigns/': typeof OOrgIdCampaignsIndexRoute
  '/o/$orgId/payments/': typeof OOrgIdPaymentsIndexRoute
  '/o/$orgId/campaigns/$campaignId/settings': typeof OOrgIdCampaignsCampaignIdSettingsRoute
  '/o/$orgId/campaigns/$campaignId/sharing': typeof OOrgIdCampaignsCampaignIdSharingRoute
  '/o/$orgId/campaigns/$campaignId/': typeof OOrgIdCampaignsCampaignIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/onboarding'
    | '/o/$orgId'
    | '/login'
    | '/magic-code'
    | '/$'
    | '/about-us'
    | '/blocks-showcase'
    | '/home'
    | '/pricing'
    | '/s'
    | '/support'
    | '/live/$slug'
    | '/onboarding/verify'
    | '/r2/$'
    | '/'
    | '/app'
    | '/onboarding/'
    | '/d/$donationId'
    | '/discover/$category'
    | '/api/auth/$'
    | '/d/$donationId/donation-status'
    | '/f/$slug/donate'
    | '/o/$orgId/account'
    | '/o/$orgId/campaigns'
    | '/o/$orgId/donations'
    | '/o/$orgId/finance'
    | '/o/$orgId/payments'
    | '/discover'
    | '/o/$orgId/'
    | '/o/$orgId/account/kyc'
    | '/o/$orgId/account/security'
    | '/o/$orgId/campaign-previews/$campaignId'
    | '/o/$orgId/campaigns/$campaignId'
    | '/o/$orgId/payments/withdrawal-accounts'
    | '/o/$orgId/payments/withdrawal-history'
    | '/f/$slug'
    | '/o/$orgId/account/'
    | '/o/$orgId/campaigns/'
    | '/o/$orgId/payments/'
    | '/o/$orgId/campaigns/$campaignId/settings'
    | '/o/$orgId/campaigns/$campaignId/sharing'
    | '/o/$orgId/campaigns/$campaignId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/magic-code'
    | '/$'
    | '/about-us'
    | '/blocks-showcase'
    | '/home'
    | '/pricing'
    | '/s'
    | '/support'
    | '/live/$slug'
    | '/onboarding/verify'
    | '/r2/$'
    | '/'
    | '/app'
    | '/onboarding'
    | '/d/$donationId'
    | '/discover/$category'
    | '/api/auth/$'
    | '/d/$donationId/donation-status'
    | '/f/$slug/donate'
    | '/o/$orgId/donations'
    | '/o/$orgId/finance'
    | '/discover'
    | '/o/$orgId'
    | '/o/$orgId/account/kyc'
    | '/o/$orgId/account/security'
    | '/o/$orgId/campaign-previews/$campaignId'
    | '/o/$orgId/payments/withdrawal-accounts'
    | '/o/$orgId/payments/withdrawal-history'
    | '/f/$slug'
    | '/o/$orgId/account'
    | '/o/$orgId/campaigns'
    | '/o/$orgId/payments'
    | '/o/$orgId/campaigns/$campaignId/settings'
    | '/o/$orgId/campaigns/$campaignId/sharing'
    | '/o/$orgId/campaigns/$campaignId'
  id:
    | '__root__'
    | '/_auth'
    | '/_public'
    | '/onboarding'
    | '/o/$orgId'
    | '/_auth/login'
    | '/_auth/magic-code'
    | '/_public/$'
    | '/_public/about-us'
    | '/_public/blocks-showcase'
    | '/_public/home'
    | '/_public/pricing'
    | '/_public/s'
    | '/_public/support'
    | '/live/$slug'
    | '/onboarding/verify'
    | '/r2/$'
    | '/_public/'
    | '/app/'
    | '/onboarding/'
    | '/_public/d/$donationId'
    | '/_public/discover/$category'
    | '/api/auth/$'
    | '/d/$donationId/donation-status'
    | '/f/$slug/donate'
    | '/o/$orgId/account'
    | '/o/$orgId/campaigns'
    | '/o/$orgId/donations'
    | '/o/$orgId/finance'
    | '/o/$orgId/payments'
    | '/_public/discover/'
    | '/o/$orgId/'
    | '/o/$orgId/account/kyc'
    | '/o/$orgId/account/security'
    | '/o/$orgId/campaign-previews/$campaignId'
    | '/o/$orgId/campaigns/$campaignId'
    | '/o/$orgId/payments/withdrawal-accounts'
    | '/o/$orgId/payments/withdrawal-history'
    | '/_public/f/$slug/'
    | '/o/$orgId/account/'
    | '/o/$orgId/campaigns/'
    | '/o/$orgId/payments/'
    | '/o/$orgId/campaigns/$campaignId/settings'
    | '/o/$orgId/campaigns/$campaignId/sharing'
    | '/o/$orgId/campaigns/$campaignId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  OnboardingRouteRoute: typeof OnboardingRouteRouteWithChildren
  OOrgIdRouteRoute: typeof OOrgIdRouteRouteWithChildren
  LiveSlugRoute: typeof LiveSlugRoute
  R2SplatRoute: typeof R2SplatRoute
  AppIndexRoute: typeof AppIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  DDonationIdDonationStatusRoute: typeof DDonationIdDonationStatusRoute
  FSlugDonateRoute: typeof FSlugDonateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/r2/$': {
      id: '/r2/$'
      path: '/r2/$'
      fullPath: '/r2/$'
      preLoaderRoute: typeof R2SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/verify': {
      id: '/onboarding/verify'
      path: '/verify'
      fullPath: '/onboarding/verify'
      preLoaderRoute: typeof OnboardingVerifyRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/live/$slug': {
      id: '/live/$slug'
      path: '/live/$slug'
      fullPath: '/live/$slug'
      preLoaderRoute: typeof LiveSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/support': {
      id: '/_public/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof PublicSupportRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/s': {
      id: '/_public/s'
      path: '/s'
      fullPath: '/s'
      preLoaderRoute: typeof PublicSRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/pricing': {
      id: '/_public/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PublicPricingRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/home': {
      id: '/_public/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof PublicHomeRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/blocks-showcase': {
      id: '/_public/blocks-showcase'
      path: '/blocks-showcase'
      fullPath: '/blocks-showcase'
      preLoaderRoute: typeof PublicBlocksShowcaseRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/about-us': {
      id: '/_public/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof PublicAboutUsRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/$': {
      id: '/_public/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof PublicSplatRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_auth/magic-code': {
      id: '/_auth/magic-code'
      path: '/magic-code'
      fullPath: '/magic-code'
      preLoaderRoute: typeof AuthMagicCodeRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/o/$orgId': {
      id: '/o/$orgId'
      path: '/o/$orgId'
      fullPath: '/o/$orgId'
      preLoaderRoute: typeof OOrgIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o/$orgId/': {
      id: '/o/$orgId/'
      path: '/'
      fullPath: '/o/$orgId/'
      preLoaderRoute: typeof OOrgIdIndexRouteImport
      parentRoute: typeof OOrgIdRouteRoute
    }
    '/_public/discover/': {
      id: '/_public/discover/'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof PublicDiscoverIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/o/$orgId/payments': {
      id: '/o/$orgId/payments'
      path: '/payments'
      fullPath: '/o/$orgId/payments'
      preLoaderRoute: typeof OOrgIdPaymentsRouteImport
      parentRoute: typeof OOrgIdRouteRoute
    }
    '/o/$orgId/finance': {
      id: '/o/$orgId/finance'
      path: '/finance'
      fullPath: '/o/$orgId/finance'
      preLoaderRoute: typeof OOrgIdFinanceRouteImport
      parentRoute: typeof OOrgIdRouteRoute
    }
    '/o/$orgId/donations': {
      id: '/o/$orgId/donations'
      path: '/donations'
      fullPath: '/o/$orgId/donations'
      preLoaderRoute: typeof OOrgIdDonationsRouteImport
      parentRoute: typeof OOrgIdRouteRoute
    }
    '/o/$orgId/campaigns': {
      id: '/o/$orgId/campaigns'
      path: '/campaigns'
      fullPath: '/o/$orgId/campaigns'
      preLoaderRoute: typeof OOrgIdCampaignsRouteImport
      parentRoute: typeof OOrgIdRouteRoute
    }
    '/o/$orgId/account': {
      id: '/o/$orgId/account'
      path: '/account'
      fullPath: '/o/$orgId/account'
      preLoaderRoute: typeof OOrgIdAccountRouteImport
      parentRoute: typeof OOrgIdRouteRoute
    }
    '/f/$slug/donate': {
      id: '/f/$slug/donate'
      path: '/f/$slug/donate'
      fullPath: '/f/$slug/donate'
      preLoaderRoute: typeof FSlugDonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/d/$donationId/donation-status': {
      id: '/d/$donationId/donation-status'
      path: '/d/$donationId/donation-status'
      fullPath: '/d/$donationId/donation-status'
      preLoaderRoute: typeof DDonationIdDonationStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/discover/$category': {
      id: '/_public/discover/$category'
      path: '/discover/$category'
      fullPath: '/discover/$category'
      preLoaderRoute: typeof PublicDiscoverCategoryRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/d/$donationId': {
      id: '/_public/d/$donationId'
      path: '/d/$donationId'
      fullPath: '/d/$donationId'
      preLoaderRoute: typeof PublicDDonationIdRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/o/$orgId/payments/': {
      id: '/o/$orgId/payments/'
      path: '/'
      fullPath: '/o/$orgId/payments/'
      preLoaderRoute: typeof OOrgIdPaymentsIndexRouteImport
      parentRoute: typeof OOrgIdPaymentsRoute
    }
    '/o/$orgId/campaigns/': {
      id: '/o/$orgId/campaigns/'
      path: '/'
      fullPath: '/o/$orgId/campaigns/'
      preLoaderRoute: typeof OOrgIdCampaignsIndexRouteImport
      parentRoute: typeof OOrgIdCampaignsRoute
    }
    '/o/$orgId/account/': {
      id: '/o/$orgId/account/'
      path: '/'
      fullPath: '/o/$orgId/account/'
      preLoaderRoute: typeof OOrgIdAccountIndexRouteImport
      parentRoute: typeof OOrgIdAccountRoute
    }
    '/_public/f/$slug/': {
      id: '/_public/f/$slug/'
      path: '/f/$slug'
      fullPath: '/f/$slug'
      preLoaderRoute: typeof PublicFSlugIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/o/$orgId/payments/withdrawal-history': {
      id: '/o/$orgId/payments/withdrawal-history'
      path: '/withdrawal-history'
      fullPath: '/o/$orgId/payments/withdrawal-history'
      preLoaderRoute: typeof OOrgIdPaymentsWithdrawalHistoryRouteImport
      parentRoute: typeof OOrgIdPaymentsRoute
    }
    '/o/$orgId/payments/withdrawal-accounts': {
      id: '/o/$orgId/payments/withdrawal-accounts'
      path: '/withdrawal-accounts'
      fullPath: '/o/$orgId/payments/withdrawal-accounts'
      preLoaderRoute: typeof OOrgIdPaymentsWithdrawalAccountsRouteImport
      parentRoute: typeof OOrgIdPaymentsRoute
    }
    '/o/$orgId/campaigns/$campaignId': {
      id: '/o/$orgId/campaigns/$campaignId'
      path: '/$campaignId'
      fullPath: '/o/$orgId/campaigns/$campaignId'
      preLoaderRoute: typeof OOrgIdCampaignsCampaignIdRouteImport
      parentRoute: typeof OOrgIdCampaignsRoute
    }
    '/o/$orgId/campaign-previews/$campaignId': {
      id: '/o/$orgId/campaign-previews/$campaignId'
      path: '/campaign-previews/$campaignId'
      fullPath: '/o/$orgId/campaign-previews/$campaignId'
      preLoaderRoute: typeof OOrgIdCampaignPreviewsCampaignIdRouteImport
      parentRoute: typeof OOrgIdRouteRoute
    }
    '/o/$orgId/account/security': {
      id: '/o/$orgId/account/security'
      path: '/security'
      fullPath: '/o/$orgId/account/security'
      preLoaderRoute: typeof OOrgIdAccountSecurityRouteImport
      parentRoute: typeof OOrgIdAccountRoute
    }
    '/o/$orgId/account/kyc': {
      id: '/o/$orgId/account/kyc'
      path: '/kyc'
      fullPath: '/o/$orgId/account/kyc'
      preLoaderRoute: typeof OOrgIdAccountKycRouteImport
      parentRoute: typeof OOrgIdAccountRoute
    }
    '/o/$orgId/campaigns/$campaignId/': {
      id: '/o/$orgId/campaigns/$campaignId/'
      path: '/'
      fullPath: '/o/$orgId/campaigns/$campaignId/'
      preLoaderRoute: typeof OOrgIdCampaignsCampaignIdIndexRouteImport
      parentRoute: typeof OOrgIdCampaignsCampaignIdRoute
    }
    '/o/$orgId/campaigns/$campaignId/sharing': {
      id: '/o/$orgId/campaigns/$campaignId/sharing'
      path: '/sharing'
      fullPath: '/o/$orgId/campaigns/$campaignId/sharing'
      preLoaderRoute: typeof OOrgIdCampaignsCampaignIdSharingRouteImport
      parentRoute: typeof OOrgIdCampaignsCampaignIdRoute
    }
    '/o/$orgId/campaigns/$campaignId/settings': {
      id: '/o/$orgId/campaigns/$campaignId/settings'
      path: '/settings'
      fullPath: '/o/$orgId/campaigns/$campaignId/settings'
      preLoaderRoute: typeof OOrgIdCampaignsCampaignIdSettingsRouteImport
      parentRoute: typeof OOrgIdCampaignsCampaignIdRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthMagicCodeRoute: typeof AuthMagicCodeRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthMagicCodeRoute: AuthMagicCodeRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface PublicRouteRouteChildren {
  PublicSplatRoute: typeof PublicSplatRoute
  PublicAboutUsRoute: typeof PublicAboutUsRoute
  PublicBlocksShowcaseRoute: typeof PublicBlocksShowcaseRoute
  PublicHomeRoute: typeof PublicHomeRoute
  PublicPricingRoute: typeof PublicPricingRoute
  PublicSRoute: typeof PublicSRoute
  PublicSupportRoute: typeof PublicSupportRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicDDonationIdRoute: typeof PublicDDonationIdRoute
  PublicDiscoverCategoryRoute: typeof PublicDiscoverCategoryRoute
  PublicDiscoverIndexRoute: typeof PublicDiscoverIndexRoute
  PublicFSlugIndexRoute: typeof PublicFSlugIndexRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicSplatRoute: PublicSplatRoute,
  PublicAboutUsRoute: PublicAboutUsRoute,
  PublicBlocksShowcaseRoute: PublicBlocksShowcaseRoute,
  PublicHomeRoute: PublicHomeRoute,
  PublicPricingRoute: PublicPricingRoute,
  PublicSRoute: PublicSRoute,
  PublicSupportRoute: PublicSupportRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicDDonationIdRoute: PublicDDonationIdRoute,
  PublicDiscoverCategoryRoute: PublicDiscoverCategoryRoute,
  PublicDiscoverIndexRoute: PublicDiscoverIndexRoute,
  PublicFSlugIndexRoute: PublicFSlugIndexRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

interface OnboardingRouteRouteChildren {
  OnboardingVerifyRoute: typeof OnboardingVerifyRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

const OnboardingRouteRouteChildren: OnboardingRouteRouteChildren = {
  OnboardingVerifyRoute: OnboardingVerifyRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
}

const OnboardingRouteRouteWithChildren = OnboardingRouteRoute._addFileChildren(
  OnboardingRouteRouteChildren,
)

interface OOrgIdAccountRouteChildren {
  OOrgIdAccountKycRoute: typeof OOrgIdAccountKycRoute
  OOrgIdAccountSecurityRoute: typeof OOrgIdAccountSecurityRoute
  OOrgIdAccountIndexRoute: typeof OOrgIdAccountIndexRoute
}

const OOrgIdAccountRouteChildren: OOrgIdAccountRouteChildren = {
  OOrgIdAccountKycRoute: OOrgIdAccountKycRoute,
  OOrgIdAccountSecurityRoute: OOrgIdAccountSecurityRoute,
  OOrgIdAccountIndexRoute: OOrgIdAccountIndexRoute,
}

const OOrgIdAccountRouteWithChildren = OOrgIdAccountRoute._addFileChildren(
  OOrgIdAccountRouteChildren,
)

interface OOrgIdCampaignsCampaignIdRouteChildren {
  OOrgIdCampaignsCampaignIdSettingsRoute: typeof OOrgIdCampaignsCampaignIdSettingsRoute
  OOrgIdCampaignsCampaignIdSharingRoute: typeof OOrgIdCampaignsCampaignIdSharingRoute
  OOrgIdCampaignsCampaignIdIndexRoute: typeof OOrgIdCampaignsCampaignIdIndexRoute
}

const OOrgIdCampaignsCampaignIdRouteChildren: OOrgIdCampaignsCampaignIdRouteChildren =
  {
    OOrgIdCampaignsCampaignIdSettingsRoute:
      OOrgIdCampaignsCampaignIdSettingsRoute,
    OOrgIdCampaignsCampaignIdSharingRoute:
      OOrgIdCampaignsCampaignIdSharingRoute,
    OOrgIdCampaignsCampaignIdIndexRoute: OOrgIdCampaignsCampaignIdIndexRoute,
  }

const OOrgIdCampaignsCampaignIdRouteWithChildren =
  OOrgIdCampaignsCampaignIdRoute._addFileChildren(
    OOrgIdCampaignsCampaignIdRouteChildren,
  )

interface OOrgIdCampaignsRouteChildren {
  OOrgIdCampaignsCampaignIdRoute: typeof OOrgIdCampaignsCampaignIdRouteWithChildren
  OOrgIdCampaignsIndexRoute: typeof OOrgIdCampaignsIndexRoute
}

const OOrgIdCampaignsRouteChildren: OOrgIdCampaignsRouteChildren = {
  OOrgIdCampaignsCampaignIdRoute: OOrgIdCampaignsCampaignIdRouteWithChildren,
  OOrgIdCampaignsIndexRoute: OOrgIdCampaignsIndexRoute,
}

const OOrgIdCampaignsRouteWithChildren = OOrgIdCampaignsRoute._addFileChildren(
  OOrgIdCampaignsRouteChildren,
)

interface OOrgIdPaymentsRouteChildren {
  OOrgIdPaymentsWithdrawalAccountsRoute: typeof OOrgIdPaymentsWithdrawalAccountsRoute
  OOrgIdPaymentsWithdrawalHistoryRoute: typeof OOrgIdPaymentsWithdrawalHistoryRoute
  OOrgIdPaymentsIndexRoute: typeof OOrgIdPaymentsIndexRoute
}

const OOrgIdPaymentsRouteChildren: OOrgIdPaymentsRouteChildren = {
  OOrgIdPaymentsWithdrawalAccountsRoute: OOrgIdPaymentsWithdrawalAccountsRoute,
  OOrgIdPaymentsWithdrawalHistoryRoute: OOrgIdPaymentsWithdrawalHistoryRoute,
  OOrgIdPaymentsIndexRoute: OOrgIdPaymentsIndexRoute,
}

const OOrgIdPaymentsRouteWithChildren = OOrgIdPaymentsRoute._addFileChildren(
  OOrgIdPaymentsRouteChildren,
)

interface OOrgIdRouteRouteChildren {
  OOrgIdAccountRoute: typeof OOrgIdAccountRouteWithChildren
  OOrgIdCampaignsRoute: typeof OOrgIdCampaignsRouteWithChildren
  OOrgIdDonationsRoute: typeof OOrgIdDonationsRoute
  OOrgIdFinanceRoute: typeof OOrgIdFinanceRoute
  OOrgIdPaymentsRoute: typeof OOrgIdPaymentsRouteWithChildren
  OOrgIdIndexRoute: typeof OOrgIdIndexRoute
  OOrgIdCampaignPreviewsCampaignIdRoute: typeof OOrgIdCampaignPreviewsCampaignIdRoute
}

const OOrgIdRouteRouteChildren: OOrgIdRouteRouteChildren = {
  OOrgIdAccountRoute: OOrgIdAccountRouteWithChildren,
  OOrgIdCampaignsRoute: OOrgIdCampaignsRouteWithChildren,
  OOrgIdDonationsRoute: OOrgIdDonationsRoute,
  OOrgIdFinanceRoute: OOrgIdFinanceRoute,
  OOrgIdPaymentsRoute: OOrgIdPaymentsRouteWithChildren,
  OOrgIdIndexRoute: OOrgIdIndexRoute,
  OOrgIdCampaignPreviewsCampaignIdRoute: OOrgIdCampaignPreviewsCampaignIdRoute,
}

const OOrgIdRouteRouteWithChildren = OOrgIdRouteRoute._addFileChildren(
  OOrgIdRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
  OnboardingRouteRoute: OnboardingRouteRouteWithChildren,
  OOrgIdRouteRoute: OOrgIdRouteRouteWithChildren,
  LiveSlugRoute: LiveSlugRoute,
  R2SplatRoute: R2SplatRoute,
  AppIndexRoute: AppIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  DDonationIdDonationStatusRoute: DDonationIdDonationStatusRoute,
  FSlugDonateRoute: FSlugDonateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.tsx'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
