/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteRouteImport } from './routes/onboarding/route'
import { Route as UnauthenticatedRouteRouteImport } from './routes/_unauthenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as R2SplatRouteImport } from './routes/r2.$'
import { Route as OnboardingVerifyRouteImport } from './routes/onboarding/verify'
import { Route as UnauthenticatedMagicCodeRouteImport } from './routes/_unauthenticated/magic-code'
import { Route as UnauthenticatedLoginRouteImport } from './routes/_unauthenticated/login'
import { Route as OOrgIdRouteRouteImport } from './routes/o.$orgId/route'
import { Route as OOrgIdIndexRouteImport } from './routes/o.$orgId/index'
import { Route as OOrgIdPaymentsRouteImport } from './routes/o.$orgId/payments'
import { Route as OOrgIdFinanceRouteImport } from './routes/o.$orgId/finance'
import { Route as OOrgIdDonationsRouteImport } from './routes/o.$orgId/donations'
import { Route as OOrgIdCampaignsRouteImport } from './routes/o.$orgId/campaigns'
import { Route as OOrgIdAccountRouteImport } from './routes/o.$orgId/account'
import { Route as ApiWebhooksSmileRouteImport } from './routes/api/webhooks/smile'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as OOrgIdPaymentsIndexRouteImport } from './routes/o.$orgId/payments/index'
import { Route as OOrgIdCampaignsIndexRouteImport } from './routes/o.$orgId/campaigns/index'
import { Route as OOrgIdAccountIndexRouteImport } from './routes/o.$orgId/account/index'
import { Route as OOrgIdPaymentsWithdrawalHistoryRouteImport } from './routes/o.$orgId/payments/withdrawal-history'
import { Route as OOrgIdPaymentsWithdrawalAccountsRouteImport } from './routes/o.$orgId/payments/withdrawal-accounts'
import { Route as OOrgIdCampaignsCampaignIdRouteImport } from './routes/o.$orgId/campaigns.$campaignId'
import { Route as OOrgIdAccountSecurityRouteImport } from './routes/o.$orgId/account/security'
import { Route as OOrgIdAccountKycRouteImport } from './routes/o.$orgId/account/kyc'
import { Route as OOrgIdCampaignsCampaignIdIndexRouteImport } from './routes/o.$orgId/campaigns.$campaignId/index'
import { Route as OOrgIdCampaignsCampaignIdSharingRouteImport } from './routes/o.$orgId/campaigns.$campaignId/sharing'
import { Route as OOrgIdCampaignsCampaignIdSettingsRouteImport } from './routes/o.$orgId/campaigns.$campaignId/settings'

const OnboardingRouteRoute = OnboardingRouteRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthenticatedRouteRoute = UnauthenticatedRouteRouteImport.update({
  id: '/_unauthenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any)
const R2SplatRoute = R2SplatRouteImport.update({
  id: '/r2/$',
  path: '/r2/$',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingVerifyRoute = OnboardingVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const UnauthenticatedMagicCodeRoute =
  UnauthenticatedMagicCodeRouteImport.update({
    id: '/magic-code',
    path: '/magic-code',
    getParentRoute: () => UnauthenticatedRouteRoute,
  } as any)
const UnauthenticatedLoginRoute = UnauthenticatedLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => UnauthenticatedRouteRoute,
} as any)
const OOrgIdRouteRoute = OOrgIdRouteRouteImport.update({
  id: '/o/$orgId',
  path: '/o/$orgId',
  getParentRoute: () => rootRouteImport,
} as any)
const OOrgIdIndexRoute = OOrgIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OOrgIdRouteRoute,
} as any)
const OOrgIdPaymentsRoute = OOrgIdPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => OOrgIdRouteRoute,
} as any)
const OOrgIdFinanceRoute = OOrgIdFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => OOrgIdRouteRoute,
} as any)
const OOrgIdDonationsRoute = OOrgIdDonationsRouteImport.update({
  id: '/donations',
  path: '/donations',
  getParentRoute: () => OOrgIdRouteRoute,
} as any)
const OOrgIdCampaignsRoute = OOrgIdCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => OOrgIdRouteRoute,
} as any)
const OOrgIdAccountRoute = OOrgIdAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => OOrgIdRouteRoute,
} as any)
const ApiWebhooksSmileRoute = ApiWebhooksSmileRouteImport.update({
  id: '/api/webhooks/smile',
  path: '/api/webhooks/smile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const OOrgIdPaymentsIndexRoute = OOrgIdPaymentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OOrgIdPaymentsRoute,
} as any)
const OOrgIdCampaignsIndexRoute = OOrgIdCampaignsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OOrgIdCampaignsRoute,
} as any)
const OOrgIdAccountIndexRoute = OOrgIdAccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OOrgIdAccountRoute,
} as any)
const OOrgIdPaymentsWithdrawalHistoryRoute =
  OOrgIdPaymentsWithdrawalHistoryRouteImport.update({
    id: '/withdrawal-history',
    path: '/withdrawal-history',
    getParentRoute: () => OOrgIdPaymentsRoute,
  } as any)
const OOrgIdPaymentsWithdrawalAccountsRoute =
  OOrgIdPaymentsWithdrawalAccountsRouteImport.update({
    id: '/withdrawal-accounts',
    path: '/withdrawal-accounts',
    getParentRoute: () => OOrgIdPaymentsRoute,
  } as any)
const OOrgIdCampaignsCampaignIdRoute =
  OOrgIdCampaignsCampaignIdRouteImport.update({
    id: '/$campaignId',
    path: '/$campaignId',
    getParentRoute: () => OOrgIdCampaignsRoute,
  } as any)
const OOrgIdAccountSecurityRoute = OOrgIdAccountSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => OOrgIdAccountRoute,
} as any)
const OOrgIdAccountKycRoute = OOrgIdAccountKycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => OOrgIdAccountRoute,
} as any)
const OOrgIdCampaignsCampaignIdIndexRoute =
  OOrgIdCampaignsCampaignIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => OOrgIdCampaignsCampaignIdRoute,
  } as any)
const OOrgIdCampaignsCampaignIdSharingRoute =
  OOrgIdCampaignsCampaignIdSharingRouteImport.update({
    id: '/sharing',
    path: '/sharing',
    getParentRoute: () => OOrgIdCampaignsCampaignIdRoute,
  } as any)
const OOrgIdCampaignsCampaignIdSettingsRoute =
  OOrgIdCampaignsCampaignIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => OOrgIdCampaignsCampaignIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRouteRouteWithChildren
  '/o/$orgId': typeof OOrgIdRouteRouteWithChildren
  '/login': typeof UnauthenticatedLoginRoute
  '/magic-code': typeof UnauthenticatedMagicCodeRoute
  '/onboarding/verify': typeof OnboardingVerifyRoute
  '/r2/$': typeof R2SplatRoute
  '/app': typeof AppIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/webhooks/smile': typeof ApiWebhooksSmileRoute
  '/o/$orgId/account': typeof OOrgIdAccountRouteWithChildren
  '/o/$orgId/campaigns': typeof OOrgIdCampaignsRouteWithChildren
  '/o/$orgId/donations': typeof OOrgIdDonationsRoute
  '/o/$orgId/finance': typeof OOrgIdFinanceRoute
  '/o/$orgId/payments': typeof OOrgIdPaymentsRouteWithChildren
  '/o/$orgId/': typeof OOrgIdIndexRoute
  '/o/$orgId/account/kyc': typeof OOrgIdAccountKycRoute
  '/o/$orgId/account/security': typeof OOrgIdAccountSecurityRoute
  '/o/$orgId/campaigns/$campaignId': typeof OOrgIdCampaignsCampaignIdRouteWithChildren
  '/o/$orgId/payments/withdrawal-accounts': typeof OOrgIdPaymentsWithdrawalAccountsRoute
  '/o/$orgId/payments/withdrawal-history': typeof OOrgIdPaymentsWithdrawalHistoryRoute
  '/o/$orgId/account/': typeof OOrgIdAccountIndexRoute
  '/o/$orgId/campaigns/': typeof OOrgIdCampaignsIndexRoute
  '/o/$orgId/payments/': typeof OOrgIdPaymentsIndexRoute
  '/o/$orgId/campaigns/$campaignId/settings': typeof OOrgIdCampaignsCampaignIdSettingsRoute
  '/o/$orgId/campaigns/$campaignId/sharing': typeof OOrgIdCampaignsCampaignIdSharingRoute
  '/o/$orgId/campaigns/$campaignId/': typeof OOrgIdCampaignsCampaignIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof UnauthenticatedLoginRoute
  '/magic-code': typeof UnauthenticatedMagicCodeRoute
  '/onboarding/verify': typeof OnboardingVerifyRoute
  '/r2/$': typeof R2SplatRoute
  '/app': typeof AppIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/webhooks/smile': typeof ApiWebhooksSmileRoute
  '/o/$orgId/donations': typeof OOrgIdDonationsRoute
  '/o/$orgId/finance': typeof OOrgIdFinanceRoute
  '/o/$orgId': typeof OOrgIdIndexRoute
  '/o/$orgId/account/kyc': typeof OOrgIdAccountKycRoute
  '/o/$orgId/account/security': typeof OOrgIdAccountSecurityRoute
  '/o/$orgId/payments/withdrawal-accounts': typeof OOrgIdPaymentsWithdrawalAccountsRoute
  '/o/$orgId/payments/withdrawal-history': typeof OOrgIdPaymentsWithdrawalHistoryRoute
  '/o/$orgId/account': typeof OOrgIdAccountIndexRoute
  '/o/$orgId/campaigns': typeof OOrgIdCampaignsIndexRoute
  '/o/$orgId/payments': typeof OOrgIdPaymentsIndexRoute
  '/o/$orgId/campaigns/$campaignId/settings': typeof OOrgIdCampaignsCampaignIdSettingsRoute
  '/o/$orgId/campaigns/$campaignId/sharing': typeof OOrgIdCampaignsCampaignIdSharingRoute
  '/o/$orgId/campaigns/$campaignId': typeof OOrgIdCampaignsCampaignIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_unauthenticated': typeof UnauthenticatedRouteRouteWithChildren
  '/onboarding': typeof OnboardingRouteRouteWithChildren
  '/o/$orgId': typeof OOrgIdRouteRouteWithChildren
  '/_unauthenticated/login': typeof UnauthenticatedLoginRoute
  '/_unauthenticated/magic-code': typeof UnauthenticatedMagicCodeRoute
  '/onboarding/verify': typeof OnboardingVerifyRoute
  '/r2/$': typeof R2SplatRoute
  '/app/': typeof AppIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/webhooks/smile': typeof ApiWebhooksSmileRoute
  '/o/$orgId/account': typeof OOrgIdAccountRouteWithChildren
  '/o/$orgId/campaigns': typeof OOrgIdCampaignsRouteWithChildren
  '/o/$orgId/donations': typeof OOrgIdDonationsRoute
  '/o/$orgId/finance': typeof OOrgIdFinanceRoute
  '/o/$orgId/payments': typeof OOrgIdPaymentsRouteWithChildren
  '/o/$orgId/': typeof OOrgIdIndexRoute
  '/o/$orgId/account/kyc': typeof OOrgIdAccountKycRoute
  '/o/$orgId/account/security': typeof OOrgIdAccountSecurityRoute
  '/o/$orgId/campaigns/$campaignId': typeof OOrgIdCampaignsCampaignIdRouteWithChildren
  '/o/$orgId/payments/withdrawal-accounts': typeof OOrgIdPaymentsWithdrawalAccountsRoute
  '/o/$orgId/payments/withdrawal-history': typeof OOrgIdPaymentsWithdrawalHistoryRoute
  '/o/$orgId/account/': typeof OOrgIdAccountIndexRoute
  '/o/$orgId/campaigns/': typeof OOrgIdCampaignsIndexRoute
  '/o/$orgId/payments/': typeof OOrgIdPaymentsIndexRoute
  '/o/$orgId/campaigns/$campaignId/settings': typeof OOrgIdCampaignsCampaignIdSettingsRoute
  '/o/$orgId/campaigns/$campaignId/sharing': typeof OOrgIdCampaignsCampaignIdSharingRoute
  '/o/$orgId/campaigns/$campaignId/': typeof OOrgIdCampaignsCampaignIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/o/$orgId'
    | '/login'
    | '/magic-code'
    | '/onboarding/verify'
    | '/r2/$'
    | '/app'
    | '/onboarding/'
    | '/api/auth/$'
    | '/api/webhooks/smile'
    | '/o/$orgId/account'
    | '/o/$orgId/campaigns'
    | '/o/$orgId/donations'
    | '/o/$orgId/finance'
    | '/o/$orgId/payments'
    | '/o/$orgId/'
    | '/o/$orgId/account/kyc'
    | '/o/$orgId/account/security'
    | '/o/$orgId/campaigns/$campaignId'
    | '/o/$orgId/payments/withdrawal-accounts'
    | '/o/$orgId/payments/withdrawal-history'
    | '/o/$orgId/account/'
    | '/o/$orgId/campaigns/'
    | '/o/$orgId/payments/'
    | '/o/$orgId/campaigns/$campaignId/settings'
    | '/o/$orgId/campaigns/$campaignId/sharing'
    | '/o/$orgId/campaigns/$campaignId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/magic-code'
    | '/onboarding/verify'
    | '/r2/$'
    | '/app'
    | '/onboarding'
    | '/api/auth/$'
    | '/api/webhooks/smile'
    | '/o/$orgId/donations'
    | '/o/$orgId/finance'
    | '/o/$orgId'
    | '/o/$orgId/account/kyc'
    | '/o/$orgId/account/security'
    | '/o/$orgId/payments/withdrawal-accounts'
    | '/o/$orgId/payments/withdrawal-history'
    | '/o/$orgId/account'
    | '/o/$orgId/campaigns'
    | '/o/$orgId/payments'
    | '/o/$orgId/campaigns/$campaignId/settings'
    | '/o/$orgId/campaigns/$campaignId/sharing'
    | '/o/$orgId/campaigns/$campaignId'
  id:
    | '__root__'
    | '/'
    | '/_unauthenticated'
    | '/onboarding'
    | '/o/$orgId'
    | '/_unauthenticated/login'
    | '/_unauthenticated/magic-code'
    | '/onboarding/verify'
    | '/r2/$'
    | '/app/'
    | '/onboarding/'
    | '/api/auth/$'
    | '/api/webhooks/smile'
    | '/o/$orgId/account'
    | '/o/$orgId/campaigns'
    | '/o/$orgId/donations'
    | '/o/$orgId/finance'
    | '/o/$orgId/payments'
    | '/o/$orgId/'
    | '/o/$orgId/account/kyc'
    | '/o/$orgId/account/security'
    | '/o/$orgId/campaigns/$campaignId'
    | '/o/$orgId/payments/withdrawal-accounts'
    | '/o/$orgId/payments/withdrawal-history'
    | '/o/$orgId/account/'
    | '/o/$orgId/campaigns/'
    | '/o/$orgId/payments/'
    | '/o/$orgId/campaigns/$campaignId/settings'
    | '/o/$orgId/campaigns/$campaignId/sharing'
    | '/o/$orgId/campaigns/$campaignId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UnauthenticatedRouteRoute: typeof UnauthenticatedRouteRouteWithChildren
  OnboardingRouteRoute: typeof OnboardingRouteRouteWithChildren
  OOrgIdRouteRoute: typeof OOrgIdRouteRouteWithChildren
  R2SplatRoute: typeof R2SplatRoute
  AppIndexRoute: typeof AppIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiWebhooksSmileRoute: typeof ApiWebhooksSmileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_unauthenticated': {
      id: '/_unauthenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof UnauthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r2/$': {
      id: '/r2/$'
      path: '/r2/$'
      fullPath: '/r2/$'
      preLoaderRoute: typeof R2SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/verify': {
      id: '/onboarding/verify'
      path: '/verify'
      fullPath: '/onboarding/verify'
      preLoaderRoute: typeof OnboardingVerifyRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/_unauthenticated/magic-code': {
      id: '/_unauthenticated/magic-code'
      path: '/magic-code'
      fullPath: '/magic-code'
      preLoaderRoute: typeof UnauthenticatedMagicCodeRouteImport
      parentRoute: typeof UnauthenticatedRouteRoute
    }
    '/_unauthenticated/login': {
      id: '/_unauthenticated/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof UnauthenticatedLoginRouteImport
      parentRoute: typeof UnauthenticatedRouteRoute
    }
    '/o/$orgId': {
      id: '/o/$orgId'
      path: '/o/$orgId'
      fullPath: '/o/$orgId'
      preLoaderRoute: typeof OOrgIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o/$orgId/': {
      id: '/o/$orgId/'
      path: '/'
      fullPath: '/o/$orgId/'
      preLoaderRoute: typeof OOrgIdIndexRouteImport
      parentRoute: typeof OOrgIdRouteRoute
    }
    '/o/$orgId/payments': {
      id: '/o/$orgId/payments'
      path: '/payments'
      fullPath: '/o/$orgId/payments'
      preLoaderRoute: typeof OOrgIdPaymentsRouteImport
      parentRoute: typeof OOrgIdRouteRoute
    }
    '/o/$orgId/finance': {
      id: '/o/$orgId/finance'
      path: '/finance'
      fullPath: '/o/$orgId/finance'
      preLoaderRoute: typeof OOrgIdFinanceRouteImport
      parentRoute: typeof OOrgIdRouteRoute
    }
    '/o/$orgId/donations': {
      id: '/o/$orgId/donations'
      path: '/donations'
      fullPath: '/o/$orgId/donations'
      preLoaderRoute: typeof OOrgIdDonationsRouteImport
      parentRoute: typeof OOrgIdRouteRoute
    }
    '/o/$orgId/campaigns': {
      id: '/o/$orgId/campaigns'
      path: '/campaigns'
      fullPath: '/o/$orgId/campaigns'
      preLoaderRoute: typeof OOrgIdCampaignsRouteImport
      parentRoute: typeof OOrgIdRouteRoute
    }
    '/o/$orgId/account': {
      id: '/o/$orgId/account'
      path: '/account'
      fullPath: '/o/$orgId/account'
      preLoaderRoute: typeof OOrgIdAccountRouteImport
      parentRoute: typeof OOrgIdRouteRoute
    }
    '/api/webhooks/smile': {
      id: '/api/webhooks/smile'
      path: '/api/webhooks/smile'
      fullPath: '/api/webhooks/smile'
      preLoaderRoute: typeof ApiWebhooksSmileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o/$orgId/payments/': {
      id: '/o/$orgId/payments/'
      path: '/'
      fullPath: '/o/$orgId/payments/'
      preLoaderRoute: typeof OOrgIdPaymentsIndexRouteImport
      parentRoute: typeof OOrgIdPaymentsRoute
    }
    '/o/$orgId/campaigns/': {
      id: '/o/$orgId/campaigns/'
      path: '/'
      fullPath: '/o/$orgId/campaigns/'
      preLoaderRoute: typeof OOrgIdCampaignsIndexRouteImport
      parentRoute: typeof OOrgIdCampaignsRoute
    }
    '/o/$orgId/account/': {
      id: '/o/$orgId/account/'
      path: '/'
      fullPath: '/o/$orgId/account/'
      preLoaderRoute: typeof OOrgIdAccountIndexRouteImport
      parentRoute: typeof OOrgIdAccountRoute
    }
    '/o/$orgId/payments/withdrawal-history': {
      id: '/o/$orgId/payments/withdrawal-history'
      path: '/withdrawal-history'
      fullPath: '/o/$orgId/payments/withdrawal-history'
      preLoaderRoute: typeof OOrgIdPaymentsWithdrawalHistoryRouteImport
      parentRoute: typeof OOrgIdPaymentsRoute
    }
    '/o/$orgId/payments/withdrawal-accounts': {
      id: '/o/$orgId/payments/withdrawal-accounts'
      path: '/withdrawal-accounts'
      fullPath: '/o/$orgId/payments/withdrawal-accounts'
      preLoaderRoute: typeof OOrgIdPaymentsWithdrawalAccountsRouteImport
      parentRoute: typeof OOrgIdPaymentsRoute
    }
    '/o/$orgId/campaigns/$campaignId': {
      id: '/o/$orgId/campaigns/$campaignId'
      path: '/$campaignId'
      fullPath: '/o/$orgId/campaigns/$campaignId'
      preLoaderRoute: typeof OOrgIdCampaignsCampaignIdRouteImport
      parentRoute: typeof OOrgIdCampaignsRoute
    }
    '/o/$orgId/account/security': {
      id: '/o/$orgId/account/security'
      path: '/security'
      fullPath: '/o/$orgId/account/security'
      preLoaderRoute: typeof OOrgIdAccountSecurityRouteImport
      parentRoute: typeof OOrgIdAccountRoute
    }
    '/o/$orgId/account/kyc': {
      id: '/o/$orgId/account/kyc'
      path: '/kyc'
      fullPath: '/o/$orgId/account/kyc'
      preLoaderRoute: typeof OOrgIdAccountKycRouteImport
      parentRoute: typeof OOrgIdAccountRoute
    }
    '/o/$orgId/campaigns/$campaignId/': {
      id: '/o/$orgId/campaigns/$campaignId/'
      path: '/'
      fullPath: '/o/$orgId/campaigns/$campaignId/'
      preLoaderRoute: typeof OOrgIdCampaignsCampaignIdIndexRouteImport
      parentRoute: typeof OOrgIdCampaignsCampaignIdRoute
    }
    '/o/$orgId/campaigns/$campaignId/sharing': {
      id: '/o/$orgId/campaigns/$campaignId/sharing'
      path: '/sharing'
      fullPath: '/o/$orgId/campaigns/$campaignId/sharing'
      preLoaderRoute: typeof OOrgIdCampaignsCampaignIdSharingRouteImport
      parentRoute: typeof OOrgIdCampaignsCampaignIdRoute
    }
    '/o/$orgId/campaigns/$campaignId/settings': {
      id: '/o/$orgId/campaigns/$campaignId/settings'
      path: '/settings'
      fullPath: '/o/$orgId/campaigns/$campaignId/settings'
      preLoaderRoute: typeof OOrgIdCampaignsCampaignIdSettingsRouteImport
      parentRoute: typeof OOrgIdCampaignsCampaignIdRoute
    }
  }
}

interface UnauthenticatedRouteRouteChildren {
  UnauthenticatedLoginRoute: typeof UnauthenticatedLoginRoute
  UnauthenticatedMagicCodeRoute: typeof UnauthenticatedMagicCodeRoute
}

const UnauthenticatedRouteRouteChildren: UnauthenticatedRouteRouteChildren = {
  UnauthenticatedLoginRoute: UnauthenticatedLoginRoute,
  UnauthenticatedMagicCodeRoute: UnauthenticatedMagicCodeRoute,
}

const UnauthenticatedRouteRouteWithChildren =
  UnauthenticatedRouteRoute._addFileChildren(UnauthenticatedRouteRouteChildren)

interface OnboardingRouteRouteChildren {
  OnboardingVerifyRoute: typeof OnboardingVerifyRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

const OnboardingRouteRouteChildren: OnboardingRouteRouteChildren = {
  OnboardingVerifyRoute: OnboardingVerifyRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
}

const OnboardingRouteRouteWithChildren = OnboardingRouteRoute._addFileChildren(
  OnboardingRouteRouteChildren,
)

interface OOrgIdAccountRouteChildren {
  OOrgIdAccountKycRoute: typeof OOrgIdAccountKycRoute
  OOrgIdAccountSecurityRoute: typeof OOrgIdAccountSecurityRoute
  OOrgIdAccountIndexRoute: typeof OOrgIdAccountIndexRoute
}

const OOrgIdAccountRouteChildren: OOrgIdAccountRouteChildren = {
  OOrgIdAccountKycRoute: OOrgIdAccountKycRoute,
  OOrgIdAccountSecurityRoute: OOrgIdAccountSecurityRoute,
  OOrgIdAccountIndexRoute: OOrgIdAccountIndexRoute,
}

const OOrgIdAccountRouteWithChildren = OOrgIdAccountRoute._addFileChildren(
  OOrgIdAccountRouteChildren,
)

interface OOrgIdCampaignsCampaignIdRouteChildren {
  OOrgIdCampaignsCampaignIdSettingsRoute: typeof OOrgIdCampaignsCampaignIdSettingsRoute
  OOrgIdCampaignsCampaignIdSharingRoute: typeof OOrgIdCampaignsCampaignIdSharingRoute
  OOrgIdCampaignsCampaignIdIndexRoute: typeof OOrgIdCampaignsCampaignIdIndexRoute
}

const OOrgIdCampaignsCampaignIdRouteChildren: OOrgIdCampaignsCampaignIdRouteChildren =
  {
    OOrgIdCampaignsCampaignIdSettingsRoute:
      OOrgIdCampaignsCampaignIdSettingsRoute,
    OOrgIdCampaignsCampaignIdSharingRoute:
      OOrgIdCampaignsCampaignIdSharingRoute,
    OOrgIdCampaignsCampaignIdIndexRoute: OOrgIdCampaignsCampaignIdIndexRoute,
  }

const OOrgIdCampaignsCampaignIdRouteWithChildren =
  OOrgIdCampaignsCampaignIdRoute._addFileChildren(
    OOrgIdCampaignsCampaignIdRouteChildren,
  )

interface OOrgIdCampaignsRouteChildren {
  OOrgIdCampaignsCampaignIdRoute: typeof OOrgIdCampaignsCampaignIdRouteWithChildren
  OOrgIdCampaignsIndexRoute: typeof OOrgIdCampaignsIndexRoute
}

const OOrgIdCampaignsRouteChildren: OOrgIdCampaignsRouteChildren = {
  OOrgIdCampaignsCampaignIdRoute: OOrgIdCampaignsCampaignIdRouteWithChildren,
  OOrgIdCampaignsIndexRoute: OOrgIdCampaignsIndexRoute,
}

const OOrgIdCampaignsRouteWithChildren = OOrgIdCampaignsRoute._addFileChildren(
  OOrgIdCampaignsRouteChildren,
)

interface OOrgIdPaymentsRouteChildren {
  OOrgIdPaymentsWithdrawalAccountsRoute: typeof OOrgIdPaymentsWithdrawalAccountsRoute
  OOrgIdPaymentsWithdrawalHistoryRoute: typeof OOrgIdPaymentsWithdrawalHistoryRoute
  OOrgIdPaymentsIndexRoute: typeof OOrgIdPaymentsIndexRoute
}

const OOrgIdPaymentsRouteChildren: OOrgIdPaymentsRouteChildren = {
  OOrgIdPaymentsWithdrawalAccountsRoute: OOrgIdPaymentsWithdrawalAccountsRoute,
  OOrgIdPaymentsWithdrawalHistoryRoute: OOrgIdPaymentsWithdrawalHistoryRoute,
  OOrgIdPaymentsIndexRoute: OOrgIdPaymentsIndexRoute,
}

const OOrgIdPaymentsRouteWithChildren = OOrgIdPaymentsRoute._addFileChildren(
  OOrgIdPaymentsRouteChildren,
)

interface OOrgIdRouteRouteChildren {
  OOrgIdAccountRoute: typeof OOrgIdAccountRouteWithChildren
  OOrgIdCampaignsRoute: typeof OOrgIdCampaignsRouteWithChildren
  OOrgIdDonationsRoute: typeof OOrgIdDonationsRoute
  OOrgIdFinanceRoute: typeof OOrgIdFinanceRoute
  OOrgIdPaymentsRoute: typeof OOrgIdPaymentsRouteWithChildren
  OOrgIdIndexRoute: typeof OOrgIdIndexRoute
}

const OOrgIdRouteRouteChildren: OOrgIdRouteRouteChildren = {
  OOrgIdAccountRoute: OOrgIdAccountRouteWithChildren,
  OOrgIdCampaignsRoute: OOrgIdCampaignsRouteWithChildren,
  OOrgIdDonationsRoute: OOrgIdDonationsRoute,
  OOrgIdFinanceRoute: OOrgIdFinanceRoute,
  OOrgIdPaymentsRoute: OOrgIdPaymentsRouteWithChildren,
  OOrgIdIndexRoute: OOrgIdIndexRoute,
}

const OOrgIdRouteRouteWithChildren = OOrgIdRouteRoute._addFileChildren(
  OOrgIdRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UnauthenticatedRouteRoute: UnauthenticatedRouteRouteWithChildren,
  OnboardingRouteRoute: OnboardingRouteRouteWithChildren,
  OOrgIdRouteRoute: OOrgIdRouteRouteWithChildren,
  R2SplatRoute: R2SplatRoute,
  AppIndexRoute: AppIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiWebhooksSmileRoute: ApiWebhooksSmileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.tsx'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
