/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    exports: Export;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    exports: ExportsSelect<false> | ExportsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    settings: Setting;
  };
  globalsSelect: {
    settings: SettingsSelect<false> | SettingsSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: {
      createCollectionExport: TaskCreateCollectionExport;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tablet?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * Used for page routing (e.g., /pricing, /about, /how-it-works)
   */
  slug: string;
  description?: string | null;
  blocks: (
    | HeroBlock
    | DividerBlock
    | ThreeColumnCardBlock
    | CalculatorBlock
    | FAQBlock
    | AccordionBlock
    | CTABlock
    | RichTextBlock
    | ImageVideoBlock
    | StatsBlock
    | FeatureHighlightBlock
    | TwoColumnBlock
    | GalleryBlock
    | ContactFormBlock
  )[];
  published?: boolean | null;
  /**
   * When this page was published
   */
  publishedAt?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  title: string;
  subtitle?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  alignment?: ('left' | 'center' | 'right') | null;
  responsive?: {
    desktopSize?: ('small' | 'medium' | 'large') | null;
    tabletSize?: ('small' | 'medium' | 'large') | null;
    mobileSize?: ('small' | 'medium' | 'large') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DividerBlock".
 */
export interface DividerBlock {
  style?: ('thin' | 'thick' | 'dashed') | null;
  color?: ('gray-light' | 'gray-dark' | 'green-light' | 'primary') | null;
  spacing?: {
    topDesktop?: number | null;
    bottomDesktop?: number | null;
    topTablet?: number | null;
    bottomTablet?: number | null;
    topMobile?: number | null;
    bottomMobile?: number | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'divider';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ThreeColumnCardBlock".
 */
export interface ThreeColumnCardBlock {
  title?: string | null;
  subtitle?: string | null;
  columns: {
    columnTitle?: string | null;
    rows?:
      | {
          label: string;
          value: string;
          description?: {
            root: {
              type: string;
              children: {
                type: any;
                version: number;
                [k: string]: unknown;
              }[];
              direction: ('ltr' | 'rtl') | null;
              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
              indent: number;
              version: number;
            };
            [k: string]: unknown;
          } | null;
          tooltip?: string | null;
          id?: string | null;
        }[]
      | null;
    id?: string | null;
  }[];
  backgroundColor?: ('white' | 'gray-light' | 'green-light' | 'primary') | null;
  responsive?: {
    desktopColumns?: ('1' | '2' | '3') | null;
    tabletColumns?: ('1' | '2' | '3') | null;
    mobileColumns?: ('1' | '2' | '3') | null;
    gapDesktop?: number | null;
    gapTablet?: number | null;
    gapMobile?: number | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'three-column-card';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CalculatorBlock".
 */
export interface CalculatorBlock {
  title: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  examples?:
    | {
        totalRaised: number;
        numberOfDonors: number;
        averageDonationAmount?: number | null;
        id?: string | null;
      }[]
    | null;
  feeConfiguration: {
    /**
     * Paystack fee for all payment methods
     */
    transactionFeePercentage: number;
    /**
     * Optional percentage you take (currently 0%)
     */
    donorContributionPercentage?: number | null;
  };
  responsive?: {
    desktopColumns?: ('2' | '3') | null;
    tabletColumns?: ('1' | '2') | null;
    mobileColumns?: '1' | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'calculator';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FAQBlock".
 */
export interface FAQBlock {
  title?: string | null;
  faqs?:
    | {
        question: string;
        answer: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  displayStyle?: ('accordion' | 'expanded' | 'two-column') | null;
  responsive?: {
    tabletDisplayStyle?: ('accordion' | 'expanded' | 'two-column') | null;
    mobileDisplayStyle?: ('accordion' | 'expanded') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'faq';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AccordionBlock".
 */
export interface AccordionBlock {
  title?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  items?:
    | {
        title: string;
        content: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        icon?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * If unchecked, only one item can be open at a time
   */
  allowMultipleOpen?: boolean | null;
  /**
   * Which item should be open by default (0 = first item, -1 = none)
   */
  defaultOpenIndex?: number | null;
  backgroundColor?: ('white' | 'gray-light' | 'green-light' | 'primary') | null;
  responsive?: {
    maxWidth?: ('full' | 'large' | 'medium' | 'small') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'accordion';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CTABlock".
 */
export interface CTABlock {
  title: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  buttons?:
    | {
        buttonText: string;
        buttonLink: string;
        buttonStyle?: ('primary' | 'secondary' | 'outline') | null;
        buttonSize?: ('small' | 'medium' | 'large') | null;
        id?: string | null;
      }[]
    | null;
  alignment?: ('left' | 'center' | 'right') | null;
  backgroundColor?: ('white' | 'gray-light' | 'green-light' | 'primary') | null;
  responsive?: {
    buttonStackMobile?: boolean | null;
    buttonStackTablet?: boolean | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock".
 */
export interface RichTextBlock {
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  alignment?: ('left' | 'center' | 'right') | null;
  maxWidth?: ('full' | 'large' | 'medium' | 'small') | null;
  spacing?: {
    topDesktop?: number | null;
    bottomDesktop?: number | null;
    topTablet?: number | null;
    bottomTablet?: number | null;
    topMobile?: number | null;
    bottomMobile?: number | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'rich-text';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageVideoBlock".
 */
export interface ImageVideoBlock {
  mediaType: 'image' | 'video';
  image?: (number | null) | Media;
  /**
   * YouTube or Vimeo URL (e.g., https://www.youtube.com/watch?v=...)
   */
  videoUrl?: string | null;
  caption?: string | null;
  altText?: string | null;
  alignment?: ('left' | 'center' | 'right') | null;
  width?: ('full' | 'large' | 'medium' | 'small') | null;
  spacing?: {
    topDesktop?: number | null;
    bottomDesktop?: number | null;
    topTablet?: number | null;
    bottomTablet?: number | null;
    topMobile?: number | null;
    bottomMobile?: number | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'image-video';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsBlock".
 */
export interface StatsBlock {
  title?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  stats?:
    | {
        /**
         * e.g., 1M, 10K, GHS 1B
         */
        value: string;
        /**
         * e.g., Funds Raised, Supporters, Communities
         */
        label: string;
        icon?: (number | null) | Media;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  layout?: ('2' | '3' | '4') | null;
  backgroundColor?: ('white' | 'gray-light' | 'green-light' | 'primary') | null;
  responsive?: {
    tabletColumns?: ('1' | '2' | '3') | null;
    mobileColumns?: ('1' | '2') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'stats';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeatureHighlightBlock".
 */
export interface FeatureHighlightBlock {
  title?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  features?:
    | {
        icon: number | Media;
        title: string;
        description?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  layout?: ('2' | '3' | '4') | null;
  iconSize?: ('small' | 'medium' | 'large') | null;
  alignment?: ('left' | 'center') | null;
  backgroundColor?: ('white' | 'gray-light' | 'green-light' | 'primary') | null;
  responsive?: {
    tabletColumns?: ('1' | '2' | '3') | null;
    mobileColumns?: ('1' | '2') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'feature-highlight';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TwoColumnBlock".
 */
export interface TwoColumnBlock {
  leftContent: {
    contentType: 'text' | 'media';
    text?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    image?: (number | null) | Media;
    /**
     * YouTube or Vimeo URL
     */
    videoUrl?: string | null;
  };
  rightContent: {
    contentType: 'text' | 'media';
    text?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    image?: (number | null) | Media;
    /**
     * YouTube or Vimeo URL
     */
    videoUrl?: string | null;
  };
  backgroundColor?: ('white' | 'gray-light' | 'green-light' | 'primary') | null;
  responsive?: {
    columnRatio?: ('50-50' | '60-40' | '40-60') | null;
    /**
     * Useful for alternating layouts on multiple blocks
     */
    reverseOrder?: boolean | null;
    stackMobile?: boolean | null;
    gap?: number | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'two-column';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GalleryBlock".
 */
export interface GalleryBlock {
  title?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  images?:
    | {
        image: number | Media;
        caption?: string | null;
        alt?: string | null;
        id?: string | null;
      }[]
    | null;
  layout?: ('2' | '3' | '4' | 'masonry') | null;
  enableLightbox?: boolean | null;
  responsive?: {
    tabletColumns?: ('1' | '2' | '3' | 'masonry') | null;
    mobileColumns?: ('1' | '2' | 'masonry') | null;
    gap?: number | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'gallery';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactFormBlock".
 */
export interface ContactFormBlock {
  title?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  formFields?:
    | {
        label: string;
        /**
         * Used for form submission (e.g., first_name, email, message)
         */
        name: string;
        type: 'text' | 'email' | 'tel' | 'number' | 'textarea' | 'select' | 'checkbox' | 'radio';
        required?: boolean | null;
        placeholder?: string | null;
        options?:
          | {
              label: string;
              value: string;
              id?: string | null;
            }[]
          | null;
        rows?: number | null;
        id?: string | null;
      }[]
    | null;
  submitButtonText?: string | null;
  successMessage?: string | null;
  errorMessage?: string | null;
  /**
   * Form submissions will be sent to this email
   */
  recipientEmail: string;
  layout?: ('single' | 'two') | null;
  backgroundColor?: ('white' | 'gray-light' | 'green-light' | 'primary') | null;
  maxWidth?: ('full' | 'large' | 'medium' | 'small') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'contact-form';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exports".
 */
export interface Export {
  id: number;
  name?: string | null;
  format?: ('csv' | 'json') | null;
  limit?: number | null;
  page?: number | null;
  sort?: string | null;
  sortOrder?: ('asc' | 'desc') | null;
  drafts?: ('yes' | 'no') | null;
  selectionToUse?: ('currentSelection' | 'currentFilters' | 'all') | null;
  fields?: string[] | null;
  collectionSlug: string;
  where?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'createCollectionExport';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'createCollectionExport') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'exports';
        value: number | Export;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        tablet?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  blocks?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
        divider?: T | DividerBlockSelect<T>;
        'three-column-card'?: T | ThreeColumnCardBlockSelect<T>;
        calculator?: T | CalculatorBlockSelect<T>;
        faq?: T | FAQBlockSelect<T>;
        accordion?: T | AccordionBlockSelect<T>;
        cta?: T | CTABlockSelect<T>;
        'rich-text'?: T | RichTextBlockSelect<T>;
        'image-video'?: T | ImageVideoBlockSelect<T>;
        stats?: T | StatsBlockSelect<T>;
        'feature-highlight'?: T | FeatureHighlightBlockSelect<T>;
        'two-column'?: T | TwoColumnBlockSelect<T>;
        gallery?: T | GalleryBlockSelect<T>;
        'contact-form'?: T | ContactFormBlockSelect<T>;
      };
  published?: T;
  publishedAt?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock_select".
 */
export interface HeroBlockSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  description?: T;
  alignment?: T;
  responsive?:
    | T
    | {
        desktopSize?: T;
        tabletSize?: T;
        mobileSize?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DividerBlock_select".
 */
export interface DividerBlockSelect<T extends boolean = true> {
  style?: T;
  color?: T;
  spacing?:
    | T
    | {
        topDesktop?: T;
        bottomDesktop?: T;
        topTablet?: T;
        bottomTablet?: T;
        topMobile?: T;
        bottomMobile?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ThreeColumnCardBlock_select".
 */
export interface ThreeColumnCardBlockSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  columns?:
    | T
    | {
        columnTitle?: T;
        rows?:
          | T
          | {
              label?: T;
              value?: T;
              description?: T;
              tooltip?: T;
              id?: T;
            };
        id?: T;
      };
  backgroundColor?: T;
  responsive?:
    | T
    | {
        desktopColumns?: T;
        tabletColumns?: T;
        mobileColumns?: T;
        gapDesktop?: T;
        gapTablet?: T;
        gapMobile?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CalculatorBlock_select".
 */
export interface CalculatorBlockSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  examples?:
    | T
    | {
        totalRaised?: T;
        numberOfDonors?: T;
        averageDonationAmount?: T;
        id?: T;
      };
  feeConfiguration?:
    | T
    | {
        transactionFeePercentage?: T;
        donorContributionPercentage?: T;
      };
  responsive?:
    | T
    | {
        desktopColumns?: T;
        tabletColumns?: T;
        mobileColumns?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FAQBlock_select".
 */
export interface FAQBlockSelect<T extends boolean = true> {
  title?: T;
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  displayStyle?: T;
  responsive?:
    | T
    | {
        tabletDisplayStyle?: T;
        mobileDisplayStyle?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AccordionBlock_select".
 */
export interface AccordionBlockSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  items?:
    | T
    | {
        title?: T;
        content?: T;
        icon?: T;
        id?: T;
      };
  allowMultipleOpen?: T;
  defaultOpenIndex?: T;
  backgroundColor?: T;
  responsive?:
    | T
    | {
        maxWidth?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CTABlock_select".
 */
export interface CTABlockSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  buttons?:
    | T
    | {
        buttonText?: T;
        buttonLink?: T;
        buttonStyle?: T;
        buttonSize?: T;
        id?: T;
      };
  alignment?: T;
  backgroundColor?: T;
  responsive?:
    | T
    | {
        buttonStackMobile?: T;
        buttonStackTablet?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock_select".
 */
export interface RichTextBlockSelect<T extends boolean = true> {
  content?: T;
  alignment?: T;
  maxWidth?: T;
  spacing?:
    | T
    | {
        topDesktop?: T;
        bottomDesktop?: T;
        topTablet?: T;
        bottomTablet?: T;
        topMobile?: T;
        bottomMobile?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageVideoBlock_select".
 */
export interface ImageVideoBlockSelect<T extends boolean = true> {
  mediaType?: T;
  image?: T;
  videoUrl?: T;
  caption?: T;
  altText?: T;
  alignment?: T;
  width?: T;
  spacing?:
    | T
    | {
        topDesktop?: T;
        bottomDesktop?: T;
        topTablet?: T;
        bottomTablet?: T;
        topMobile?: T;
        bottomMobile?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsBlock_select".
 */
export interface StatsBlockSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        icon?: T;
        description?: T;
        id?: T;
      };
  layout?: T;
  backgroundColor?: T;
  responsive?:
    | T
    | {
        tabletColumns?: T;
        mobileColumns?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeatureHighlightBlock_select".
 */
export interface FeatureHighlightBlockSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  features?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  layout?: T;
  iconSize?: T;
  alignment?: T;
  backgroundColor?: T;
  responsive?:
    | T
    | {
        tabletColumns?: T;
        mobileColumns?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TwoColumnBlock_select".
 */
export interface TwoColumnBlockSelect<T extends boolean = true> {
  leftContent?:
    | T
    | {
        contentType?: T;
        text?: T;
        image?: T;
        videoUrl?: T;
      };
  rightContent?:
    | T
    | {
        contentType?: T;
        text?: T;
        image?: T;
        videoUrl?: T;
      };
  backgroundColor?: T;
  responsive?:
    | T
    | {
        columnRatio?: T;
        reverseOrder?: T;
        stackMobile?: T;
        gap?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GalleryBlock_select".
 */
export interface GalleryBlockSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  images?:
    | T
    | {
        image?: T;
        caption?: T;
        alt?: T;
        id?: T;
      };
  layout?: T;
  enableLightbox?: T;
  responsive?:
    | T
    | {
        tabletColumns?: T;
        mobileColumns?: T;
        gap?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactFormBlock_select".
 */
export interface ContactFormBlockSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  formFields?:
    | T
    | {
        label?: T;
        name?: T;
        type?: T;
        required?: T;
        placeholder?: T;
        options?:
          | T
          | {
              label?: T;
              value?: T;
              id?: T;
            };
        rows?: T;
        id?: T;
      };
  submitButtonText?: T;
  successMessage?: T;
  errorMessage?: T;
  recipientEmail?: T;
  layout?: T;
  backgroundColor?: T;
  maxWidth?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exports_select".
 */
export interface ExportsSelect<T extends boolean = true> {
  name?: T;
  format?: T;
  limit?: T;
  page?: T;
  sort?: T;
  sortOrder?: T;
  drafts?: T;
  selectionToUse?: T;
  fields?: T;
  collectionSlug?: T;
  where?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: number;
  siteName: string;
  siteDescription?: string | null;
  contactEmail?: string | null;
  supportPhone?: string | null;
  feeConfiguration: {
    /**
     * No upfront fee to create a fundraiser
     */
    creationFee: number;
    /**
     * Paystack fee charged on each donation (1.95% for all payment methods)
     */
    transactionFeePercentage: number;
    /**
     * Optional cut you take on each transaction (currently 0%)
     */
    donorContributionPercentage?: number | null;
    /**
     * Fees charged when fundraiser withdraws funds (payment processor fees only)
     */
    withdrawalFees?:
      | {
          method: 'mobile_money' | 'bank_account';
          type: 'flat' | 'percentage';
          /**
           * Enter amount in GHS for flat fees, or percentage for percentage fees
           */
          feeAmount: number;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  navigation?: {
    /**
     * Items will display left/right based on position setting
     */
    mainNav?:
      | {
          label: string;
          position: 'left' | 'right';
          url?: string | null;
          hasDropdown?: boolean | null;
          dropdownItems?:
            | {
                label: string;
                url: string;
                description?: string | null;
                icon?: (number | null) | Media;
                id?: string | null;
              }[]
            | null;
          /**
           * For CTA items like "Start a Fundraiser"
           */
          isButton?: boolean | null;
          id?: string | null;
        }[]
      | null;
    footerNav?:
      | {
          label: string;
          url: string;
          target?: ('_self' | '_blank') | null;
          id?: string | null;
        }[]
      | null;
  };
  footerContent?: {
    copyright?: string | null;
    socialLinks?:
      | {
          platform: 'twitter' | 'facebook' | 'instagram' | 'linkedin' | 'github';
          url: string;
          id?: string | null;
        }[]
      | null;
  };
  branding?: {
    logo?: (number | null) | Media;
    favicon?: (number | null) | Media;
    /**
     * e.g., #4CAF50
     */
    primaryColor?: string | null;
  };
  /**
   * e.g., https://yoursite.com
   */
  siteUrl?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  siteName?: T;
  siteDescription?: T;
  contactEmail?: T;
  supportPhone?: T;
  feeConfiguration?:
    | T
    | {
        creationFee?: T;
        transactionFeePercentage?: T;
        donorContributionPercentage?: T;
        withdrawalFees?:
          | T
          | {
              method?: T;
              type?: T;
              feeAmount?: T;
              description?: T;
              id?: T;
            };
      };
  navigation?:
    | T
    | {
        mainNav?:
          | T
          | {
              label?: T;
              position?: T;
              url?: T;
              hasDropdown?: T;
              dropdownItems?:
                | T
                | {
                    label?: T;
                    url?: T;
                    description?: T;
                    icon?: T;
                    id?: T;
                  };
              isButton?: T;
              id?: T;
            };
        footerNav?:
          | T
          | {
              label?: T;
              url?: T;
              target?: T;
              id?: T;
            };
      };
  footerContent?:
    | T
    | {
        copyright?: T;
        socialLinks?:
          | T
          | {
              platform?: T;
              url?: T;
              id?: T;
            };
      };
  branding?:
    | T
    | {
        logo?: T;
        favicon?: T;
        primaryColor?: T;
      };
  siteUrl?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskCreateCollectionExport".
 */
export interface TaskCreateCollectionExport {
  input: {
    name?: string | null;
    format?: ('csv' | 'json') | null;
    limit?: number | null;
    page?: number | null;
    sort?: string | null;
    sortOrder?: ('asc' | 'desc') | null;
    drafts?: ('yes' | 'no') | null;
    selectionToUse?: ('currentSelection' | 'currentFilters' | 'all') | null;
    fields?: string[] | null;
    collectionSlug: string;
    where?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    user?: string | null;
    userCollection?: string | null;
    exportsCollection?: string | null;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}
